language: julia

os:
  - osx
  - linux

julia:
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  # Needed to take precedence on Julia's version of Statistics
  - julia -e 'using UUIDs; write("Project.toml", replace(read("Project.toml", String), r"uuid = .*?\n" =>"uuid = \"$(uuid4())\"\n"))'
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test(; coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';

jobs:
  include:
    # additional Windows 32/64-bit jobs
    - os: windows
      arch: x64
      julia: 1.3
    - os: windows
      arch: x86
      julia: 1.3
      name: "Julia 1.3 (32bit)"
    - os: windows
      arch: x64
      julia: 1.4
    - os: windows
      arch: x86
      julia: 1.4
      name: "Julia 1.4 (32bit)"
    - os: windows
      arch: x86
      julia: nightly
      name: "Julia nightly (32bit)"
    # documentation build stage
    - stage: "Documentation"
      os: linux
      julia: 1.3
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
