environment:
  matrix:
  - julia_version: 1.2
  - julia_version: 1.3
  - julia_version: nightly

platform:
  - x86 # 32-bit
  - x64 # 64-bit

# Uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia_version: nightly

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - C:\julia\bin\julia -e "using InteractiveUtils; versioninfo();
      using UUIDs;
      # Needed to take precedence on Julia's version of Statistics
      write(\"Project.toml\", replace(read(\"Project.toml\", String), r"uuid = .*?\\\\n\" =>\"uuid = \\\\"$(uuid4())\\\\"\\\\n\"))'
      import Pkg; Pkg.build()"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
